/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Notas;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;

/**
 * 
 *
 * @author Carlos Hack
 */
public class Ventana extends javax.swing.JFrame {
    DefaultListModel listatabla = new DefaultListModel();
    modelo clase;
    int contador = 0;

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    lista.setModel(listatabla);
    }
    
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonguardardatos = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buscador = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtasignatura = new javax.swing.JTextField();
        txtnota = new javax.swing.JTextField();
        botonbuscar = new javax.swing.JButton();
        txtamaño = new javax.swing.JTextField();
        botonguardar = new javax.swing.JButton();
        nombreencontrado = new javax.swing.JTextField();
        asignaturaencontrada = new javax.swing.JTextField();
        notaencontrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOTAS Y ASIGNATURAS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel1)
                .addContainerGap(231, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jPanel3.setBackground(new java.awt.Color(51, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 760, 60));

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel4.setText("Asignatura:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        botonguardardatos.setBackground(new java.awt.Color(0, 51, 255));
        botonguardardatos.setText("GUARDAR DATOS");
        botonguardardatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardardatosActionPerformed(evt);
            }
        });
        jPanel1.add(botonguardardatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 740, 10));

        jLabel6.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel6.setText("Estudiante a buscar:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel9.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel9.setText("Nota:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        buscador.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 170, -1));

        txtnombre.setBackground(new java.awt.Color(255, 0, 0));
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 150, -1));

        txtasignatura.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtasignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 150, -1));

        txtnota.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(txtnota, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 60, -1));

        botonbuscar.setBackground(new java.awt.Color(0, 51, 255));
        botonbuscar.setText("BUSCAR");
        botonbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, 30));

        txtamaño.setBackground(new java.awt.Color(255, 0, 0));
        txtamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtamañoActionPerformed(evt);
            }
        });
        jPanel1.add(txtamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 60, -1));

        botonguardar.setBackground(new java.awt.Color(0, 0, 255));
        botonguardar.setText("GUARDAR");
        botonguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonguardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));

        nombreencontrado.setBackground(new java.awt.Color(255, 0, 0));
        nombreencontrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreencontradoActionPerformed(evt);
            }
        });
        jPanel1.add(nombreencontrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 210, -1));

        asignaturaencontrada.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(asignaturaencontrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 130, -1));

        notaencontrada.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.add(notaencontrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 90, -1));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 60, -1));

        jLabel5.setText("Asignatura");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel7.setText("Nota:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));
        jPanel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 180, 20));

        jLabel8.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel8.setText(" Numero de Estudiantes");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 200, 30));

        lista.setBackground(new java.awt.Color(255, 102, 255));
        jScrollPane1.setViewportView(lista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 230, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setText("MOSTRAR LISTA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void botonguardardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardardatosActionPerformed
        // TODO add your handling code here:
         if (contador < clase.getNroelementos()) {
            String Nombre_est = txtnombre.getText();
            clase.setNombre(Nombre_est, contador);

            String asignatura = txtasignatura.getText();
            clase.setAsignatura(asignatura, contador);

            float nota = Float.parseFloat(txtnota.getText());
            clase.setNota(contador, nota);

            contador++;
         
         }
           txtnombre.setText(null);
           txtasignatura.setText(null);
           txtnota.setText(null);
        
      
    }//GEN-LAST:event_botonguardardatosActionPerformed

    private void txtamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtamañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtamañoActionPerformed

    private void botonguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonguardarActionPerformed
        // TODO add your handling code here:
        int tamaño = Integer.parseInt(txtamaño.getText());
        clase = new modelo(tamaño);
    
        txtamaño.setText(null);
          
    }//GEN-LAST:event_botonguardarActionPerformed

    private void botonbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonbuscarActionPerformed
        // TODO add your handling code here:
        String buscando = buscador.getText();
        int arreglo = clase.buscar(buscando);
       
        if (arreglo != -1) {
            String Nombre_est = clase.getNombre(arreglo);
            nombreencontrado.setText(Nombre_est);

            String asignatura = clase.getAsignatura(arreglo);
            asignaturaencontrada.setText(asignatura);
            
            float nota = clase.getNota(arreglo);
            notaencontrada.setText(String.valueOf(nota));
            
        }else {
                 JOptionPane.showMessageDialog(null,"Estudiante no encontrado");
                    }
         buscador.setText(null);
    }//GEN-LAST:event_botonbuscarActionPerformed

    private void nombreencontradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreencontradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreencontradoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        for (int i=0; i < clase.getNroelementos(); i++){
            listatabla.add(i, " Nombre es: " + clase.getNombre(i) + " Asignatura: " + clase.getAsignatura(i)+ " Nota: " + clase.getNota(i));
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField asignaturaencontrada;
    private javax.swing.JButton botonbuscar;
    private javax.swing.JButton botonguardar;
    private javax.swing.JButton botonguardardatos;
    private javax.swing.JTextField buscador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label1;
    private javax.swing.JList<String> lista;
    private javax.swing.JTextField nombreencontrado;
    private javax.swing.JTextField notaencontrada;
    private javax.swing.JTextField txtamaño;
    private javax.swing.JTextField txtasignatura;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnota;
    // End of variables declaration//GEN-END:variables
}
